# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(default=None),
        ),
    ]
